### ISSUE TITLE
`pkg_resources is deprecated as an API` while installing lap on Win11

### ISSUE THREAD

**Issue by frankfletcher** [augmentedstartups/AS-One#65]
Can't install lap when trying to install asone under Windows 11.

````
PS F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One> python -m venv .env
PS F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One> .env\Scripts\activate
(.env) PS F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One> pip install numpy Cython
Collecting numpy
  Downloading numpy-2.0.1-cp311-cp311-win_amd64.whl (16.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 8.2 MB/s eta 0:00:00
Collecting Cython
  Downloading Cython-3.0.10-cp311-cp311-win_amd64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 9.9 MB/s eta 0:00:00
Installing collected packages: numpy, Cython
Successfully installed Cython-3.0.10 numpy-2.0.1

[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
(.env) PS F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One> python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in f:\00-code-f\personal\00-courses\augmented startups\yolo-nas + v8\00-src\as-one\.env\lib\site-packages (22.3.1)
Collecting pip
  Using cached pip-24.1.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-24.1.2
(.env) PS F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One> pip install lap
Collecting lap
  Using cached lap-0.4.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      <string>:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "<string>", line 127, in get_numpy_status
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One\.env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One\.env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One\.env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frank\AppData\Local\Temp\pip-build-env-0pzm7g96\overlay\Lib\site-packages\setuptools\build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\frank\AppData\Local\Temp\pip-build-env-0pzm7g96\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\frank\AppData\Local\Temp\pip-build-env-0pzm7g96\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 236, in <module>
        File "<string>", line 220, in setup_package
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(.env) PS F:\00-Code-F\Personal\00-COURSES\Augmented Startups\YOLO-NAS + V8\00-src\AS-One> pip list
Package    Version
---------- -------
Cython     3.0.10
numpy      2.0.1
pip        24.1.2
setuptools 65.5.0
````

**Comment by pg56714** [comment]
@frankfletcher 
conda create --name yolo python=3.10 -y
conda activate yolo

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

pip install asone

These steps work for me.
